-- Place at: migrations/add_challenge_system.sql
-- Run once against sanctions_db to add the Challenge System tables.
-- Does NOT modify any existing tables or indexes.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─── aml_cases ────────────────────────────────────────────────────────────────
-- Stores serialised AMLCaseXML documents with precomputed embeddings for
-- fast similarity retrieval.

CREATE TABLE IF NOT EXISTS aml_cases (
    id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_id        TEXT        NOT NULL,
    case_xml              TEXT        NOT NULL,
    typology_tags         TEXT[]      NOT NULL DEFAULT '{}',
    country_codes         TEXT[]      NOT NULL DEFAULT '{}',
    -- JSON-serialised float array (pgvector not available).
    -- Use GET /api/cases/{id}/similar for cosine re-ranking in Python.
    embedding             TEXT,
    reviewer_verdict      TEXT,
    reviewer_rationale    TEXT,
    review_timestamp      TIMESTAMPTZ DEFAULT NOW(),
    geopolitical_snapshot JSONB
);

-- Idempotent re-submission: upsert by transaction_id.
CREATE UNIQUE INDEX IF NOT EXISTS idx_aml_cases_txn_id
    ON aml_cases (transaction_id);

-- GIN indexes for O(1) pre-filtering in Stage 1 of similarity search.
CREATE INDEX IF NOT EXISTS idx_aml_cases_typology
    ON aml_cases USING GIN (typology_tags);

CREATE INDEX IF NOT EXISTS idx_aml_cases_countries
    ON aml_cases USING GIN (country_codes);

-- ─── challenge_log ────────────────────────────────────────────────────────────
-- One row per challenge generated by the LLM comparison engine.
-- reviewer_response is NULL until the analyst responds.

CREATE TABLE IF NOT EXISTS challenge_log (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id             UUID        REFERENCES aml_cases(id),
    similar_case_id     UUID        REFERENCES aml_cases(id),
    similarity_score    FLOAT,
    llm_challenge_text  TEXT,
    reviewer_response   TEXT,
    challenge_timestamp TIMESTAMPTZ DEFAULT NOW(),
    response_timestamp  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_challenge_log_case_id
    ON challenge_log (case_id);
